language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required
    - os: osx
      osx_image: xcode11.5

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
    sudo apt-get update -q;
    CMAKE_VERSION=3.17.3;
    CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.*}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz";
    echo CMAKE_URL=${CMAKE_URL};
    mkdir cmake-${CMAKE_VERSION} && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake-${CMAKE_VERSION};
    export PATH=${PWD}/cmake-${CMAKE_VERSION}/bin:${PATH};
    cmake --version;
  else
    cmake --version;
  fi
  
script:
  - cmake --version
